services:
  web:
    build: ./ProductCRUD
    command: /bin/sh -c /usr/src/productCRUD/django-entrypoint.sh
    volumes:
      - static_volume:/usr/src/productCRUD/staticfiles/
      - ./ProductCRUD:/usr/src/productCRUD
    expose:
      - 8000
    env_file: 
      - ./.env.dev
    restart: always

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/productCRUD/staticfiles/
    ports:
      - 8000:8000
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: