services:
  web:
    build: ./ProductCRUD
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn ProductCRUD.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - static_volume:/usr/src/productCRUD/staticfiles/
      - ./ProductCRUD:/usr/src/productCRUD
    expose:
      - 8080
    env_file:
      - ./.env.dev
    restart: always

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/productCRUD/staticfiles/
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: